### ISSUE TITLE
vagrant winrm-config doesn't detect auto-assigned forwarding for RDP

### ISSUE THREAD

**Issue by smurawski** [test-kitchen/kitchen-vagrant#224]
As noted in https://github.com/mitchellh/vagrant/issues/7174, the vagrant-winrm command always returns port 3389, regardless of what it is forwarded to.  `vagrant port` would show all the forwarded ports and their actual host based ports.

More details on the problem are in https://github.com/test-kitchen/test-kitchen/issues/1017

**Comment by smurawski** [comment]
cc @wstaples

**Comment by davidcpell** [comment]
just wanted to +1 this because I spent like 5 hours with this problem today

**Comment by americanhanko** [comment]
+1

**Comment by cheeseplus** [comment]
The fate of this issue is now bound up in https://github.com/test-kitchen/kitchen-vagrant/issues/372 as upstream Vagrant is now warning about the vagrant-winrm gem which we rather unfortunately rely on for base functionality with WinRM instances. Depending on the outcome of https://github.com/hashicorp/vagrant/issues/10204 we might have to write a plugin ourselves.

**Comment by chrisroberts** [comment]
This should be fixed via hashicorp/vagrant#10263 which is included in the 2.2.0 release. If there are any issues encountered with it, please do let us know. :smiley:

**Comment by cheeseplus** [comment]
❤️ @chrisroberts 

Closing this one out.
