### ISSUE TITLE
add option to delete vagrant created shared folders on `kitchen destroy`

### ISSUE THREAD

**Issue by sanguis** [test-kitchen/kitchen-vagrant#228]
it would be great if when I destroyed the created machine it also destroyed any created shared folders.

**Comment by mwrock** [comment]
I think that behavior belongs on the vagrant side. This can depend on vagrant provider and host but if you were to create a non-kitchen vagrant box with additional synced folders and then do a vagrant destroy, is this behavior any different?

One known flaw in vagrant's SMB synced folder plugin is it does leave orphaned shares, though hidden, on a windows host.

**Comment by sanguis** [comment]
it is a vagrant issue but the way I see it is when I run kitchen converge foo, foo_src is created and when I run kitchen destroy foo. src_foo should be deleted.

**Comment by adamleff** [comment]
Can you please elaborate on use case? If I specify a synced_folders config in my .kitchen.yml, and the host path doesn't exist, I receive an error:

```
       vm:
       * The host path of the shared folder is missing: /Users/aleff/tmp/shared1
```

The folder doesn't actually get created on the host side for me.

If you mean that folders inside of the root shared folder get created during the lifetime of the vagrant/kitchen VM (i.e. if I have /Users/aleff/tmp/shared1 synced to my Vagrant VM was /shared1, and something in my VM creates /shared1/mydata), and you're expecting Test Kitchen to remove /Users/aleff/tmp//shared1/mydata once I do a `kitchen destroy`, then I'm 👎  on this request given the complexity required to maintain before/after state and it would be a loaded gun pointed at someone's foot.

What behavior are you experiencing, and can you provide the steps to reproduce it? That will help us determine if this is a TK issue or a vagrant issue. But I agree with @mwrock - kitchen-vagrant writes out a Vagrantfile and executes `vagrant` CLI commands to achieve the desired state. If the same behavior you're describing happens when using Vagrant directly, we should ask the Vagrant maintainers to change the behavior.

**Comment by sanguis** [comment]
@adamleff sure.

There is an additional config that can be added to the sync method that is, create: yes `        - ["%{instance_name}_src", '/srv/www/omeka.dev', "create: true"  ]`. 

This will create the folder when vagrant spins up the machine.

As I have been looking into this issue I have found the https://github.com/emyl/vagrant-triggers vagrant plugin that would allow me to  do this.

So while at this point I believe @mwrock is correct this should be on the vagrant side.

Is there a way I can take advantage of this vagrant plugin from the .kitchen.yml, or should I override the Vagrantfile to do this?
`

**Comment by mwrock** [comment]
What you could do is install the plugin as usual and then add a erb template to your .kitchen yml that consumes the plugin functionality.

**Comment by sanguis** [comment]
trying it
