### ISSUE TITLE
proposal for a provision command similar to kitchen-docker's

### ISSUE THREAD

**Issue by alexharv074** [test-kitchen/kitchen-vagrant#232]
Hi all, I would like to optionally disable the Yum `fastestmirror` plugin so that I can point at a Squid cache and avoid misses.  Is that currently possible or is a new feature required.  If a new feature, any hints on how I could implement it?

**Comment by cheeseplus** [comment]
There isn't anything specific to that in kitchen-vagrant but that is because it's highly platform specific. test-kitchen itself supports setting `http_proxy`, `https_proxy`, `no_proxy` which will be inherited by the VM. You can then use your provisioner (chef/shell/ansible) to configure yum as appropriate.

**Comment by alexharv074** [comment]
It seems to me like kitchen-docker [implements](https://github.com/test-kitchen/kitchen-docker/blob/988fb087d725c56e694b894b7db5cd3741042890/lib/kitchen/driver/docker.rb#L247-L249) a `provision_command` whereas kitchen-vagrant doesn't.  I could use Ansible to disable the `fastestmirror` plugin but it really needs to occur earlier in the build.  Maybe I should ask instead should we implement `provision_command` here?

**Comment by mwrock** [comment]
would it be reasonable to create a chef recipie that disables this? (I am assuming you are using a chef provisioner) and put that recipe in the front of your test-kitchen runlist?

**Comment by cheeseplus** [comment]
While kitchen-docker does this, it does rely on the underlying system being docker and thus a fairly predictable linux

As we've mentioned typically this exact kind of provisioning is going to be handled by either:
 
* config mgmt itself (chef/ansible)
* in conjunction with or via built-in support of the proxy ENV variables we pass
* baking this into the images yourself
* using a custom vagrantfile.erb with your own shell-provisioner

kitchen-docker doesn't have the same equivalent as that last one so that is typically the shim used for these scenarios. This isn't to say I'm completely against adding a a similar feature in kitchen-vagrant but there are rich and multi-platform supported facilities currently that I believe allow for the ability to accomplish this goal.

**Comment by alexharv074** [comment]
To be clearer I'm trying to achieve with Test Kitchen what I achieved with Puppet's Beaker as described [here](http://razorconsulting.com.au/speeding-up-beaker-on-a-mac-using-squidman.html).

So as I mentioned the CM tool (in this case Ansible) simply can't be used because it kicks in too late in the build.  Managing baked images to be only used in the CI pipeline is never going to be worth the effort just to speed up a build, so that's not a solution.  Even a custom Vagrantfile seems like a bit too much complexity just to speed up a build?

I think I still feel there ought to be a provision command that kicks in before the CM tool is installed, but I'll have a think further about it.

**Comment by cheeseplus** [comment]
So there are a few things that already exist that sort of cover this in the kitchen world:

- the system level ENV proxies that can be passed through
- Example of using polipo locally https://gist.github.com/fnichol/7551540
- vagrant cachier https://github.com/fgrehm/vagrant-cachier

For the system level proxies and the polipo/squid locally you don't need to do much but you'll still need to edit the conf files for yum/apt as appropriate. Vagrant-cachier requires a custom `vagrantfile_erb` at this point but we've had lots of interest in automatically enabling it if present or at the very least making it a toggleable option.

Do any of these cover your needs? I'm happy to add a new feature but I need to also identify what about the existing methods are inadequate to get some clear requirements for said feature.

**Comment by alexharv074** [comment]
I'll have a look into Vagrant Cachier as it seems to be designed with my specific purpose in mind.

**Comment by jjasghar** [comment]
@alexharv074 :metal:

**Comment by cheeseplus** [comment]
Going to close this one out as resolved but still open to potentially adding a `provision_command` in the future if we get more traction.

**Comment by Lirt** [comment]
For anybody looking for hotfix, you can follow this guide http://www.elmund.io/2015/07/05/run-a-script-on-a-test-kitchen-vm-before-converge-starts/

Basically if you specify driver in .kitchen.yml like this:

```yml
platforms:
   - name: fedora-27
     driver:
       provision: True
       vagrantfiles:
         - fedora27_provision.rb
```

And then you specify provisioning file like that, you can for do preprovisioning steps:

```ruby
Vagrant.configure(2) do |config|
  config.vm.provision "shell", inline: <<-SHELL
     sudo dnf install -y python2
  SHELL
end
```
