### ISSUE TITLE
SSH-key is not the default created by vagrant

### ISSUE THREAD

**Issue by th31nitiate** [test-kitchen/kitchen-vagrant#341]
When you run this, it does not use the default key provided by vagrant which is located at: ~/.vagrant.d/insecure_private_key

It uses the private located at the following location: .kitchen/kitchen-vagrant/{TEST_SUITE_NAME}/.vagrant/machines/default/virtualbox/private_key

I have found a workaround but I feel like the ssh_key definition is incorrect. We could maybe have a method to install add a public key to the authorized ssh key file. The current workaround is to install default account via packer local packer build. The alternative to this was to define the key in the provisioner.

The annoying things is that this done on a per-OS basis, using things like %{platform} do not seem to work also.

////// output from run //////

           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.

**Comment by ilovemysillybanana** [comment]
I'm also experiencing this.

**Comment by cheeseplus** [comment]
I'm not sure I understand the problem here - are you saying this is an issue with the driver or the base boxes themselves? To be clear, there isn't a bug here.

**Comment by th31nitiate** [comment]
@cheeseplus I don't know whether to consider it a bug, I think we just need an option to say do not create new keys. I am not sure how to set this option from within the kitchen file.

It's not that big a deal as you can manually set the provisioner to use the newly generated key. I have peeped the code but like you say this uses the vagrant for the config.

`        if not (config[:ssh] && config[:ssh][:insert_key] == false)
          m = "Disable vagrant ssh key replacement to preserve the default key!"
          warn(m)
        end`

This section from the vagrant.rb seems to be the fix to it, however, the config parameter is not clear.

The vagrant template also has a username/password field that is not fully described. I do not mind perform a pull request on the docs if the info

**Comment by cheeseplus** [comment]
Kitchen nor kitchen-vagrant are generating these keys, Vagrant _itself_ is doing this entirely on it's own.

**Comment by th31nitiate** [comment]
I think it is kitchen which changes these keys since there is the command kitchen login which you use to log in. It looks like there is a dynamic vagrant file generated with a different working dir from ~/.vagrant.d .

I tested this using two images:
    config.vm.box = "centos/7"
    config.vm.box = "box-cutter/ubuntu1604"

When running in vagrant both these boxes keep the default keys, In kitchen, they do not.

I have found the following in my local vagrant file config .ssh.insert_key = false. I guess this might be the contributing factor in vagrant.

I think I will close this since based on your provisioner you can generally define the key or alternatively, in production, you create your own boxes and grab those via  box_url.

We can look into trying to add the option config.ssh.insert_key or at least how to manipulate it if you want. I leave that up to you to decide, I can take a shot if you would like(success not guaranteed lol).

**Comment by cheeseplus** [comment]
`config.ssh.insert_key` is true by default according to https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html which mean that if you're overriding this or the vagrant boxes come with custom/embedded Vagrantfiles then you might not notice. That key being present in the Vagrantfile isn't just contributing, it is _the_ reason you get different output.

I just tried both those images with vagrant directly and BOTH include when doing `vagrant up`

```
       default: Vagrant insecure key detected. Vagrant will automatically replace
       default: this with a newly generated keypair for better security.
```

This is all to say, this behaviour is exactly what running Vagrant directly would produce with the defaults. We could consider setting the the value forcibly to false in the case of bento boxes (since we produce those ourselves) but it's important that value be true in case one provides a custom box or alternate credentials.

**Comment by th31nitiate** [comment]
@cheeseplus I haven't tested it with it a default so I will take your word for it. Do you think we can maybe have the ability to add something to the config in order to toggle the `config.ssh.insert_key`. 

This will give us a greater deal of control over the box from within kitchen or kitchen vagrant and a fair opportunity for all provisioners. It appears as though we can surely control the value of how other values are controlled via erb methods.

What do you think?

**Comment by cheeseplus** [comment]
Don't need to take my word for it, this is coming straight from the Packer docs. I'm not sure what you mean by a "fair opportunity for all provisioners" - we leverage the Vagrant default because it accounts for busted/misconfigured base boxes.

We already provide a way to do this:
https://github.com/test-kitchen/kitchen-vagrant/blob/master/templates/Vagrantfile.erb#L66-L68

```
driver:
  ssh:
    insert_key: false
```

Alternatively, though overkill one could use https://github.com/test-kitchen/kitchen-vagrant#-vagrantfile_erb

**Comment by th31nitiate** [comment]
@cheeseplus that's the fix, I just found that and I was coming to update. I think if I had read the readme a bit more thoroughly it would have been a real help initially before the random little hacks before the code to be fair. 

However thanks so much for the assistance it is greatly appreciated :100: :100: :+1:
